(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),shell=document.getElementById('shell');
const start=document.getElementById('start'),hud=document.getElementById('hud'),gameover=document.getElementById('gameover');
const playBtn=document.getElementById('playBtn'),againBtn=document.getElementById('againBtn'),shareBtn=document.getElementById('shareBtn');
const timeEl=document.getElementById('timeHud'),scoreEl=document.getElementById('scoreHud'),livesEl=document.getElementById('livesHud');
const stageEl=document.getElementById('stageName'),nextEl=document.getElementById('nextStage'),progressFill=document.getElementById('progressFill');
const networkCount=document.getElementById('networkCount'),shieldBadge=document.getElementById('shieldBadge'),toast=document.getElementById('toast'),stageBanner=document.getElementById('stageBanner');
const madeIt=document.getElementById('madeIt'),bigScore=document.getElementById('bigScore'),sDodged=document.getElementById('sDodged'),sMoves=document.getElementById('sMoves'),sReferrals=document.getElementById('sReferrals'),sHits=document.getElementById('sHits'),resultLine=document.getElementById('resultLine');
const pips=[...document.querySelectorAll('.pip')];
const STAGES=['APPLICATION','SCREENING','INTERVIEW','FINAL'];
const BAD=[{icon:'🤖',label:'ATS'},{icon:'👻',label:'GHOST'},{icon:'👥',label:'500+'},{icon:'📹',label:'VIDEO'},{icon:'📝',label:'FORM'},{icon:'£',label:'£ TBC'}];
const GOOD=[{icon:'🤝',label:'NETWORK',value:1},{icon:'☕',label:'COFFEE',value:1},{icon:'🧑‍💼',label:'RECRUITER',value:2}];
let W=0,H=0,dpr=1,state='start',raf=0,last=0,startAt=0,elapsed=0,duration=45,stage=0;
let lanes=[0,0,0],player={lane:1,x:0,y:0,w:44,h:54,targetX:0,invUntil:0},objects=[],rowSeq=0,spawnClock=0,shake=0,laneFlash=0;
let stats={},network=0,shields=0,toastTimer=0,bannerTimer=0,bestScore=0,bestResult=0;
try{bestScore=Number(localStorage.getItem('jobdash-best-score')||0);bestResult=Number(localStorage.getItem('jobdash-best-result')||0)}catch(_){}
function resetStats(){stats={score:0,lives:3,dodged:0,moves:0,referrals:0,hits:0}}
function stageFor(t){return Math.min(3,Math.floor(t/(duration/4)))}
function resultRank(){return elapsed>=duration?5:stage+1}
function resultName(){return elapsed>=duration?'OFFER':STAGES[stage]}
function rr(x,y,w,h,r,fill,stroke){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function resize(){const r=shell.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);lanes=[W*.23,W*.5,W*.77];player.y=H-158;player.x=lanes[player.lane];player.targetX=lanes[player.lane];draw(performance.now())}
function showToast(text,ms=700){clearTimeout(toastTimer);toast.textContent=text;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),ms)}
function showStage(name,small='PROGRESS'){clearTimeout(bannerTimer);stageBanner.querySelector('small').textContent=small;stageBanner.querySelector('b').textContent=name;stageBanner.classList.add('show');bannerTimer=setTimeout(()=>stageBanner.classList.remove('show'),900)}
function updateHud(){timeEl.textContent=Math.max(0,Math.ceil(duration-elapsed));scoreEl.textContent=Math.round(stats.score).toLocaleString();livesEl.textContent='♥'.repeat(Math.max(0,stats.lives));stageEl.textContent=STAGES[stage];nextEl.textContent=stage===3?'NEXT: OFFER':`NEXT: ${STAGES[stage+1]}`;progressFill.style.width=`${Math.min(100,elapsed/duration*100)}%`;networkCount.textContent=`${network}/3`;pips.forEach((p,i)=>p.classList.toggle('on',i<network));shieldBadge.classList.toggle('off',shields<1);shieldBadge.textContent=shields?`REFERRAL ×${shields}`:'REFERRAL'}
function startGame(){resetStats();network=0;shields=0;objects=[];rowSeq=0;spawnClock=.45;elapsed=0;stage=0;shake=0;player.lane=1;player.x=lanes[1];player.targetX=lanes[1];player.invUntil=0;state='play';start.classList.add('hidden');gameover.classList.add('hidden');hud.classList.remove('hidden');startAt=performance.now();last=startAt;updateHud();showStage('APPLICATION','START HERE');cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function shuffled(){const a=[0,1,2];for(let i=2;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function spawnRow(){const order=shuffled();let blocked=1;if(stage===1&&Math.random()<.28)blocked=2;if(stage>=2&&Math.random()<(.48+stage*.08))blocked=2;const blockedLanes=order.slice(0,blocked),safe=order.slice(blocked);const row=++rowSeq;blockedLanes.forEach((lane,i)=>{const def=BAD[(row+i+stage)%BAD.length];objects.push({type:'bad',lane,y:-68,w:70,h:50,row,def,hit:false})});const pickupChance=.48;if(safe.length&&Math.random()<pickupChance){const lane=safe[Math.floor(Math.random()*safe.length)],def=GOOD[Math.random()<.22?2:Math.floor(Math.random()*2)];objects.push({type:'good',lane,y:-68,w:58,h:46,row,def,hit:false})}}
function changeLaneFromX(x){let best=0,dist=Infinity;lanes.forEach((lx,i)=>{const d=Math.abs(x-lx);if(d<dist){dist=d;best=i}});player.lane=best;player.targetX=lanes[best];laneFlash=performance.now()+180;if(navigator.vibrate)navigator.vibrate(4)}
function collide(o,now){if(o.hit)return;o.hit=true;if(o.type==='good'){stats.moves++;stats.score+=150;o.def.value===2?network=Math.min(3,network+2):network=Math.min(3,network+1);showToast(`${o.def.icon} ${o.def.label}`);if(network>=3){network=0;shields++;stats.referrals++;showToast('🤝 REFERRAL UNLOCKED',950)}if(navigator.vibrate)navigator.vibrate(8);return}
if(now<player.invUntil)return;if(shields>0){shields--;stats.score+=60;player.invUntil=now+650;showToast('🤝 REFERRAL SAVED YOU',850);if(navigator.vibrate)navigator.vibrate([8,20,8])}else{stats.lives--;stats.hits++;stats.score=Math.max(0,stats.score-180);player.invUntil=now+1050;shake=7;showToast(`${o.def.icon} ${o.def.label} — HIT`,700);if(navigator.vibrate)navigator.vibrate(18);if(stats.lives<=0){endGame(false);return}}}
function overlap(o){const ox=lanes[o.lane],px=player.x;return Math.abs(ox-px)<(o.w+player.w)*.42&&Math.abs(o.y-player.y)<(o.h+player.h)*.42}
function update(dt,now){elapsed=(now-startAt)/1000;const newStage=stageFor(elapsed);if(newStage!==stage){stage=newStage;showStage(STAGES[stage]);stats.score+=350}
const speed=255+stage*34+elapsed*1.1;spawnClock-=dt;if(spawnClock<=0){spawnRow();spawnClock=Math.max(.58,.91-stage*.075-Math.min(.08,elapsed/400))+Math.random()*.12}
player.x+=(player.targetX-player.x)*Math.min(1,dt*17);objects.forEach(o=>{o.y+=speed*dt;if(!o.hit&&overlap(o))collide(o,now)});const passedRows=new Set();objects.forEach(o=>{if(o.type==='bad'&&!o.hit&&o.y>player.y+70)passedRows.add(o.row)});if(passedRows.size){stats.dodged+=passedRows.size;stats.score+=passedRows.size*45;objects.forEach(o=>{if(passedRows.has(o.row)&&o.type==='bad')o.hit=true})}objects=objects.filter(o=>o.y<H+90&&!o.hit);stats.score+=dt*(18+stage*4);shake=Math.max(0,shake-dt*30);updateHud();if(elapsed>=duration)endGame(true)}
function drawRoad(now){ctx.fillStyle='rgba(10,25,42,.7)';ctx.fillRect(W*.1,0,W*.8,H);ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=2;ctx.setLineDash([12,16]);[W*.365,W*.635].forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()});ctx.setLineDash([]);const offset=(elapsed*220)%56;ctx.fillStyle='rgba(88,216,255,.045)';for(let y=-56+offset;y<H;y+=56)ctx.fillRect(W*.105,y,W*.79,2);if(now<laneFlash){ctx.fillStyle='rgba(88,216,255,.055)';ctx.fillRect(player.lane*0+lanes[player.lane]-W*.12,0,W*.24,H)}}
function drawPlayer(now){ctx.save();const inv=now<player.invUntil;if(inv&&Math.floor(now/80)%2===0)ctx.globalAlpha=.35;if(shields){ctx.strokeStyle='rgba(202,255,93,.65)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x,player.y,34,0,Math.PI*2);ctx.stroke()}ctx.shadowColor='rgba(88,216,255,.35)';ctx.shadowBlur=14;rr(player.x-22,player.y-27,44,54,13,'#eef5fb','rgba(88,216,255,.65)');ctx.shadowBlur=0;ctx.fillStyle='#0a1726';ctx.beginPath();ctx.arc(player.x,player.y-10,7,0,Math.PI*2);ctx.fill();rr(player.x-10,player.y,20,15,7,'#0a1726');ctx.fillStyle='#0a1726';ctx.font='900 8px system-ui';ctx.textAlign='center';ctx.fillText('YOU',player.x,player.y+22);ctx.restore()}
function drawObject(o){const x=lanes[o.lane],y=o.y;if(o.type==='bad'){ctx.save();ctx.shadowColor='rgba(255,105,121,.14)';ctx.shadowBlur=10;rr(x-o.w/2,y-o.h/2,o.w,o.h,13,'rgba(40,30,42,.96)','rgba(255,105,121,.35)');ctx.restore();ctx.textAlign='center';ctx.font='18px system-ui';ctx.fillText(o.def.icon,x,y-5);ctx.fillStyle='#ffd2d8';ctx.font='900 9px system-ui';ctx.fillText(o.def.label,x,y+16)}else{ctx.save();ctx.shadowColor='rgba(202,255,93,.35)';ctx.shadowBlur=16;rr(x-o.w/2,y-o.h/2,o.w,o.h,14,'rgba(23,49,39,.97)','rgba(202,255,93,.55)');ctx.restore();ctx.textAlign='center';ctx.font='18px system-ui';ctx.fillText(o.def.icon,x,y-4);ctx.fillStyle='#dfff9d';ctx.font='900 8px system-ui';ctx.fillText(o.def.label,x,y+15)}}
function drawGuide(now){if(elapsed>3.2)return;ctx.save();ctx.globalAlpha=.74+.2*Math.sin(now/150);ctx.fillStyle='#58d8ff';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.fillText('TAP A LANE',W/2,player.y-74);ctx.font='22px system-ui';ctx.fillText('←    •    →',W/2,player.y-47);ctx.restore()}
function draw(now){ctx.clearRect(0,0,W,H);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawRoad(now);objects.forEach(drawObject);drawPlayer(now);if(state==='play')drawGuide(now);ctx.restore()}
function endGame(success){if(state!=='play')return;state='over';cancelAnimationFrame(raf);hud.classList.add('hidden');gameover.classList.remove('hidden');if(success){elapsed=duration;stats.score+=2500;showStage('OFFER!','YOU MADE IT')}stats.score=Math.round(stats.score);const rank=success?5:stage+1;bestScore=Math.max(bestScore,stats.score);bestResult=Math.max(bestResult,rank);try{localStorage.setItem('jobdash-best-score',bestScore);localStorage.setItem('jobdash-best-result',bestResult)}catch(_){}madeIt.textContent=success?'OFFER!':resultName();bigScore.textContent=stats.score.toLocaleString();sDodged.textContent=stats.dodged;sMoves.textContent=stats.moves;sReferrals.textContent=stats.referrals;sHits.textContent=stats.hits;const bestName=bestResult>=5?'OFFER':STAGES[Math.max(0,bestResult-1)];resultLine.textContent=success?`You got the offer. Best score: ${bestScore.toLocaleString()}. Can you beat it?`:`You reached ${resultName()}. Best run: ${bestName} · ${bestScore.toLocaleString()} pts.`;draw(performance.now())}
async function share(){const text=`I made it to ${madeIt.textContent} in The Job Hunt and scored ${stats.score.toLocaleString()} points. Can you get the offer?`;try{if(navigator.share)await navigator.share({title:'The Job Hunt',text,url:location.href.split('?')[0]});else{await navigator.clipboard.writeText(text);showToast('Score copied')}}catch(e){if(e?.name!=='AbortError')showToast('Share cancelled')}}
function loop(now){if(state!=='play')return;const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt,now);draw(now);if(state==='play')raf=requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',e=>{if(state!=='play')return;const r=canvas.getBoundingClientRect();changeLaneFromX(e.clientX-r.left)});playBtn.addEventListener('click',startGame);againBtn.addEventListener('click',startGame);shareBtn.addEventListener('click',share);window.addEventListener('resize',resize);resize();draw(performance.now());
})();
