(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),shell=document.getElementById('shell');
const start=document.getElementById('start'),hud=document.getElementById('hud'),gameover=document.getElementById('gameover');
const playBtn=document.getElementById('playBtn'),againBtn=document.getElementById('againBtn'),shareBtn=document.getElementById('shareBtn');
const timeEl=document.getElementById('timeHud'),offersEl=document.getElementById('offersHud'),oppEl=document.getElementById('oppHud'),attentionEl=document.getElementById('attentionPips'),surfaceEl=document.getElementById('surfaceHud');
const toast=document.getElementById('toast'),chainToast=document.getElementById('chainToast');
const applyBtn=document.getElementById('applyBtn'),connectBtn=document.getElementById('connectBtn'),meetBtn=document.getElementById('meetBtn'),followBtn=document.getElementById('followBtn');
const resultOffer=document.getElementById('rOffers'),resultInts=document.getElementById('rInterviews'),resultOpps=document.getElementById('rOpps'),resultChain=document.getElementById('rChain'),resultSurface=document.getElementById('rSurface'),resultLine=document.getElementById('resultLine');
const actions=[applyBtn,connectBtn,meetBtn,followBtn];
const TYPES={you:{color:'#58d8ff',icon:'YOU'},role:{color:'#77d9ff',icon:'ROLE'},contact:{color:'#78f1ad',icon:'CONTACT'},event:{color:'#ffc86a',icon:'EVENT'}};
let W=0,H=0,dpr=1,state='start',raf=0,last=0,startAt=0,elapsed=0,duration=45;
let nodes=[],links=[],fx=[],attention=5,maxAttention=5,nextRecharge=0,actionCount=0,offers=0,interviews=0,opportunities=0,longestChain=1,surface=0,bestOffers=0,bestSurface=0,toastTimer=0,chainTimer=0,seq=0;
try{bestOffers=Number(localStorage.getItem('surface-best-offers')||0);bestSurface=Number(localStorage.getItem('surface-best-area')||0)}catch(_){}
function resize(){const r=shell.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(state==='start')draw(performance.now())}
function showToast(t,ms=900){clearTimeout(toastTimer);toast.textContent=t;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),ms)}
function showChain(t,ms=1050){clearTimeout(chainTimer);chainToast.textContent=t;chainToast.classList.add('show');chainTimer=setTimeout(()=>chainToast.classList.remove('show'),ms)}
function you(){return nodes[0]}
function randomPos(radiusMin=115,radiusMax=250){const y=you(),a=Math.random()*Math.PI*2,r=radiusMin+Math.random()*(radiusMax-radiusMin);return{x:Math.max(48,Math.min(W-48,y.x+Math.cos(a)*r)),y:Math.max(150,Math.min(H-190,y.y+Math.sin(a)*r))}}
function addNode(type,label,parent=null,chain=1,stage=''){const p=randomPos(type==='event'?125:100,type==='event'?210:240),n={id:++seq,type,label,x:p.x,y:p.y,r:type==='role'?31:type==='event'?28:26,parent:parent?.id||null,chain,stage,created:performance.now(),due:0,dead:false,pulse:1,source:parent?.type||'you'};nodes.push(n);if(parent)addLink(parent,n);return n}
function addLink(a,b){links.push({a:a.id,b:b.id,born:performance.now(),alpha:1})}
function byId(id){return nodes.find(n=>n.id===id)}
function burst(n,color){for(let i=0;i<12;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*90;fx.push({x:n.x,y:n.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.7,color})}}
function spend(){if(attention<=0){showToast('Your attention is spent — a little more returns soon');return false}attention--;updateHud();return true}
function resetGame(){nodes=[{id:++seq,type:'you',label:'YOU',x:W/2,y:H*.48,r:34,parent:null,chain:1,stage:'',created:performance.now(),due:0,dead:false,pulse:1,source:'you'}];links=[];fx=[];attention=5;nextRecharge=4.5;actionCount=0;offers=0;interviews=0;opportunities=0;longestChain=1;surface=0}
function startGame(){resetGame();elapsed=0;state='play';start.classList.add('hidden');gameover.classList.add('hidden');hud.classList.remove('hidden');startAt=performance.now();last=startAt;showToast('Choose where to spend your attention',1200);updateHud();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function useApply(){if(state!=='play'||!spend())return;actionCount++;const r=addNode('role','ROLE',you(),1,'APPLIED');opportunities++;r.due=performance.now()+4200;r.path='cold';showChain('APPLY → ROLE');burst(r,'#77d9ff')}
function useConnect(){if(state!=='play'||!spend())return;actionCount++;const c=addNode('contact','CONTACT',you(),2);showChain('CONNECT → CONTACT');burst(c,'#78f1ad');setTimeout(()=>{if(state!=='play'||c.dead)return;const r=addNode('role','INTRO ROLE',c,3,'SCREEN');opportunities++;r.path='intro';r.due=performance.now()+3700;longestChain=Math.max(longestChain,3);showChain('CONTACT → INTRO → ROLE');burst(r,'#77d9ff');updateHud()},1350)}
function useMeet(){if(state!=='play'||!spend())return;actionCount++;const e=addNode('event','EVENT',you(),2);showChain('MEET → EVENT');burst(e,'#ffc86a');setTimeout(()=>{if(state!=='play'||e.dead)return;const c1=addNode('contact','CONTACT',e,3),c2=addNode('contact','CONTACT',e,3);longestChain=Math.max(longestChain,3);burst(c1,'#78f1ad');burst(c2,'#78f1ad');showChain('EVENT → 2 CONTACTS');setTimeout(()=>{if(state!=='play'||c1.dead)return;const r=addNode('role','WARM ROLE',c1,4,'SCREEN');opportunities++;r.path='warm';r.due=performance.now()+2800;longestChain=Math.max(longestChain,4);showChain('MEET → CONTACT → INTRO → ROLE');burst(r,'#77d9ff');updateHud()},1500)},1100)}
function findFollowTarget(){const live=nodes.filter(n=>n.type==='role'&&!n.dead&&n.stage!=='OFFER');if(!live.length)return null;const priority={WAITING:4,SCREEN:3,INTERVIEW:2,APPLIED:1};return live.sort((a,b)=>(priority[b.stage]||0)-(priority[a.stage]||0)||(a.created-b.created))[0]}
function useFollow(){if(state!=='play')return;const target=findFollowTarget();if(!target){showToast('Nothing to follow up yet');return}if(!spend())return;actionCount++;target.pulse=2.2;const before=target.stage;if(before==='APPLIED'||before==='WAITING'){target.stage='SCREEN';target.due=performance.now()+3300;showChain('FOLLOW UP → RESPONSE')}else if(before==='SCREEN'){target.stage='INTERVIEW';interviews++;target.due=performance.now()+4300;showChain('FOLLOW UP → INTERVIEW');burst(target,'#d3ff69')}else if(before==='INTERVIEW'){makeOffer(target,'FOLLOW UP → OFFER')}updateHud()}
function makeOffer(r,label='INTERVIEW → OFFER'){if(r.stage==='OFFER')return;r.stage='OFFER';offers++;r.due=0;r.pulse=2.5;showChain(label);burst(r,'#d3ff69');updateHud()}
function resolveRole(r,now){if(!r.due||now<r.due||r.dead)return;r.due=0;if(r.stage==='APPLIED'){r.stage='WAITING';r.pulse=1.6;showToast('Cold application is waiting…',900)}else if(r.stage==='SCREEN'){r.stage='INTERVIEW';interviews++;r.pulse=2;burst(r,'#d3ff69');showChain(`${r.label} → INTERVIEW`);r.due=now+(r.path==='warm'?3200:r.path==='intro'?4300:5200)}else if(r.stage==='INTERVIEW'){if(r.path==='warm'||r.path==='intro'){makeOffer(r)}else{r.stage='WAITING';showToast('Interview stalled — follow up?',950)}}}
function updateHud(){timeEl.textContent=Math.max(0,Math.ceil(duration-elapsed));offersEl.textContent=offers;oppEl.textContent=opportunities;surface=Math.min(100,Math.round((nodes.filter(n=>!n.dead).length-1)*5+links.length*2+offers*10));surfaceEl.textContent=surface+'%';attentionEl.innerHTML=Array.from({length:maxAttention},(_,i)=>`<i class="${i<attention?'on':''}"></i>`).join('');actions.forEach(b=>b.classList.toggle('disabled',attention<=0));followBtn.classList.toggle('ready',!!findFollowTarget())}
function update(dt,now){elapsed=(now-startAt)/1000;if(elapsed>=nextRecharge&&attention<maxAttention){attention++;nextRecharge+=4.5;showToast('Attention +1',500)}else if(elapsed>=nextRecharge)nextRecharge+=4.5;nodes.forEach(n=>{if(n.type==='role')resolveRole(n,now);n.pulse=Math.max(1,n.pulse-dt*.7)});fx.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.985;p.vy*=.985;p.life-=dt});fx=fx.filter(p=>p.life>0);updateHud();if(elapsed>=duration)endGame()}
function nodeColor(n){if(n.type==='role'){if(n.stage==='OFFER')return '#d3ff69';if(n.stage==='INTERVIEW')return '#b9ff85';if(n.stage==='WAITING')return '#7d8da5'}return TYPES[n.type].color}
function drawBackdrop(){ctx.fillStyle='rgba(255,255,255,.025)';for(let i=0;i<34;i++){const x=(i*67)%W,y=(i*113)%H;ctx.beginPath();ctx.arc(x,y,1.2,0,Math.PI*2);ctx.fill()}}
function drawLinks(now){links.forEach(l=>{const a=byId(l.a),b=byId(l.b);if(!a||!b)return;const c=nodeColor(b);ctx.save();ctx.strokeStyle=c;ctx.globalAlpha=.2+.25*Math.min(1,(now-l.born)/700);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()})}
function drawNode(n,now){const c=nodeColor(n),pulse=1+(n.pulse-1)*.12;ctx.save();ctx.shadowColor=c;ctx.shadowBlur=10+(n.pulse-1)*14;ctx.globalAlpha=n.dead?.25:1;ctx.beginPath();ctx.arc(n.x,n.y,n.r*pulse,0,Math.PI*2);ctx.fillStyle='rgba(8,22,38,.96)';ctx.fill();ctx.lineWidth=n.type==='you'?3:2;ctx.strokeStyle=c;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=c;ctx.textAlign='center';ctx.font=n.type==='you'?'900 13px system-ui':'900 9px system-ui';ctx.fillText(n.type==='role'?n.stage:n.label,n.x,n.y+3);if(n.type==='role'){ctx.fillStyle='#90a3bb';ctx.font='800 7px system-ui';ctx.fillText(n.label,n.x,n.y+15)}ctx.restore()}
function draw(now){ctx.clearRect(0,0,W,H);drawBackdrop();drawLinks(now);nodes.forEach(n=>drawNode(n,now));fx.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,2.5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1})}
function endGame(){if(state!=='play')return;state='over';cancelAnimationFrame(raf);hud.classList.add('hidden');gameover.classList.remove('hidden');bestOffers=Math.max(bestOffers,offers);bestSurface=Math.max(bestSurface,surface);try{localStorage.setItem('surface-best-offers',bestOffers);localStorage.setItem('surface-best-area',bestSurface)}catch(_){}resultOffer.textContent=offers;resultInts.textContent=interviews;resultOpps.textContent=opportunities;resultChain.textContent=longestChain;resultSurface.textContent=surface+'%';resultLine.textContent=offers?`You turned activity into ${offers} offer${offers===1?'':'s'}. Best: ${bestOffers} offers · ${bestSurface}% surface area.`:`No offer this run — but you created ${opportunities} live opportunit${opportunities===1?'y':'ies'}. Best surface area: ${bestSurface}%.`;draw(performance.now())}
async function share(){const text=`I created ${opportunities} opportunities, reached ${interviews} interviews and ${offers} offers in Surface Area. Longest chain: ${longestChain}.`;try{if(navigator.share)await navigator.share({title:'Surface Area — The Job Hunt',text,url:location.href.split('?')[0]});else{await navigator.clipboard.writeText(text);showToast('Result copied')}}catch(e){if(e?.name!=='AbortError')showToast('Share cancelled')}}
function loop(now){if(state!=='play')return;const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt,now);draw(now);if(state==='play')raf=requestAnimationFrame(loop)}
applyBtn.addEventListener('click',useApply);connectBtn.addEventListener('click',useConnect);meetBtn.addEventListener('click',useMeet);followBtn.addEventListener('click',useFollow);playBtn.addEventListener('click',startGame);againBtn.addEventListener('click',startGame);shareBtn.addEventListener('click',share);window.addEventListener('resize',resize);resize();draw(performance.now());
})();